export const facebookSettings = {
  General: [
    { id: 'fb-timeout', label: 'Facebook Timeout (seconds)', type: 'number', default: 30, min: 0, max: 300, rating: 1 },
    {
      id: 'fb-messengeroverlay-toggle',
      label: 'Hide Messenger Overlay',
      type: 'checkbox',
      default: true,
      rating: 3,
      tag: 'messages',
    },
    { id: 'fb-stories-toggle', label: 'Hide Stories', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-reels-toggle', label: 'Hide Reels', type: 'checkbox', default: true, rating: 3 },
  ],
  Navigation: [
    { id: 'fb-search-toggle', label: 'Hide Searchbar', type: 'checkbox', default: true, rating: 2, tag: 'search' },
    { id: 'fb-profile-toggle', label: 'Hide Profile Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-home-toggle', label: 'Hide Home Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-video-toggle', label: 'Hide Video Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-market-toggle', label: 'Hide Marketplace Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-groups-toggle', label: 'Hide Groups Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-gaming-toggle', label: 'Hide Gaming Button', type: 'checkbox', default: true, rating: 2 },
    { id: 'fb-menu-toggle', label: 'Hide Menu Button', type: 'checkbox', default: true, rating: 2 },
    {
      id: 'fb-messages-toggle',
      label: 'Hide Messages Button',
      type: 'checkbox',
      default: true,
      rating: 2,
      tag: 'messages',
    },
    { id: 'fb-notification-toggle', label: 'Hide Notification Button', type: 'checkbox', default: true, rating: 2 },
  ],
  Home: [
    { id: 'fb-homeposts-toggle', label: 'Hide Posts', type: 'checkbox', default: false, rating: 5 },
    { id: 'fb-homeshortcuts-toggle', label: 'Hide Shortcuts', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-suggestions-toggle', label: 'Hide Suggestions', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-contacts-toggle', label: 'Hide Contacts', type: 'checkbox', default: true, rating: 3, tag: 'messages' },
    {
      id: 'fb-groupchats-toggle',
      label: 'Hide Group Chats',
      type: 'checkbox',
      default: true,
      rating: 3,
      tag: 'messages',
    },
  ],
  Pages: [
    { id: 'fb-pagesposts-toggle', label: 'Hide Posts', type: 'checkbox', default: false, rating: 5 },
    { id: 'fb-pageshortcuts-toggle', label: 'Hide Shortcuts', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-intro-toggle', label: 'Hide Intro', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-photos-toggle', label: 'Hide Recent Photos', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-pages-exempt', label: 'Pages Exempt', type: 'array', default: [] },
  ],
  Groups: [
    { id: 'fb-groupsposts-toggle', label: 'Hide Posts', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-groupshortcuts-toggle', label: 'Hide Guides', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-about-toggle', label: 'Hide About', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-recentmedia-toggle', label: 'Hide Recent Media', type: 'checkbox', default: true, rating: 3 },
    { id: 'fb-featured-toggle', label: 'Hide Featured Media', type: 'checkbox', default: true, rating: 3 },
  ],
};
